name: debug

on:
  workflow_dispatch:
    inputs:
      environment:
        description: aaa
        type: choice
        options:
          - dev
          - stg


jobs:
  show-environment:
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{github.event.inputs.environment}}

  check-test:
    runs-on: ubuntu-22.04
    environment:
      name: ${{github.event.inputs.enviroment}}
    steps:
      - run: echo aaa
