name: debug

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: aaa
        type: choice
        options:
          - dev
          - stg


jobs:
  show-enviroments:
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{github.inputs.enviroment}}

  check-test:
    runs-on: ubuntu-22.04
    environment:
      name: ${{github.inputs.enviroment}}
    steps:
      - run: echo aaa
