name: debug

on:
  workflow_dispatch:
    inputs:
      environment:
        description: aaa
        type: choice
        options:
          - dev
          - stg
      branch:
        description: branch
        type: string


jobs:
  show-inputs:
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{secrets.HOGE}}
  check-review:
    runs-on: ubuntu-22.04
    steps:
      - run: echo aaaa
  checkout:
    needs: [check-review]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
  show-environment:
    needs: [checkout]
    uses: ./.github/workflows/echo.yml
    with:
      branch: ${{github.event.inputs.branch}}
      environment: ${{github.event.inputs.environment}}
    secrets: inherit
