name: debug

on:
  workflow_dispatch:
    inputs:
      environment:
        description: aaa
        type: choice
        options:
          - dev
          - stg


jobs:
  show-environment:
    environment:
      name: ${{github.event.inputs.environment}}
    steps:
      - uses: ./.github/workflows/echo.yml
        with:
          text: aaaa
