name: debug

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: aaa
        type: choice
        options:
          - dev
          - stg


jobs:
  show-enviroments:
    steps:
      - run: echo ${{github.inputs.enviroment}}

  check-test:
    enviroment: ${{github.inputs.enviroment}}
    steps:
      - run: echo aaa
