name: debug

on:
  workflow_dispatch:
    inputs:
      environment:
        description: aaa
        type: choice
        options:
          - dev
          - stg


jobs:
  show-inputs:
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{secrets.HOGE}}
  check-review:
    runs-on: ubuntu-22.04
    environment:
      name: ${{github.event.inputs.environment}}
    steps:
      - run: echo aaaa
  show-environment:
    needs: [check-review]
    uses: ./.github/workflows/echo.yml
    with:
      text: bbbb
