name: echo

on:
  workflow_call:
    inputs:
      text:
        description: text
        type: string


jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - name: show input
        run: |
          echo 'text: ${{secrets.HOGE}}
