name: echo

on:
  workflow_call:
    inputs:
      branch:
        description: text
        type: string
      environment:
        description: text
        type: string

jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - name: github1
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.sha }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: github2
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.sha }}
      - name: show input
        run: |
          cat ./README.md
      - run: echo ${{ inputs.environment }}

