name: echo

on:
  workflow_call:
    inputs:
      text:
        description: text
        type: string


jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{github.event.input.text}}
